# .github/workflows/setup-liquibase/action.yml
name: 'Setup Liquibase Environment'
description: 'Sets up Java and Liquibase Secure'

runs:
  using: 'composite'
  steps:
    - name: Setup Java
      uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Liquibase Secure
      uses: liquibase/setup-liquibase@d22b8c008d6e54475bde84f50bafe9608ea42efb # v2
      with:
        version: '5.0.0'
        edition: 'secure'