globalVariables:
  TAG: ${LB_TAG}
  CLONED_URL: ${LB_CLONED_URL}
  
stages:

  # Validate changes
  Validation:
    actions: 
      - type: liquibase
        command: validate

  Status:
    actions:
      - type: liquibase
        command: status
        cmdArgs: {verbose: true}

      - type: control
        if: "status.changesetCount == 0"
        command: exit
        cmdArgs: {exitCode: 0, exitMessage: "Exiting with an error status of 0 because the database is up-to-date"}

  # Moved to separate flow
  # Checks-Changelog:
  #  actions:
  #    - type: liquibase
  #      command: checks run
  #      cmdArgs: {checks-scope: changelog, changeset-filter: "PENDING"}
  #      globalArgs: { reports-name: "checks-report-premerge-changelog.html"}

  Update-SQL:
    actions:
      - type: liquibase
        command: update-sql

  # Create Clone Database
  Create-EphemeralDB:
    actions:
      - type: shell
        command: |
          export SNOWSQL_PWD="${LIQUIBASE_COMMAND_PASSWORD}"
          snowsql -a "${SNOWFLAKE_ACCT_NAME}" -u "${LIQUIBASE_COMMAND_USERNAME}" --private-key-path "${LIQUIBASE_SNOWFLAKE_AUTH_PRIVATE_KEY_PATH}" --dbname "${LIQUIBASE_DATABASE_NAME}" --schemaname "${LB_SCHEMANAME}" -D S_NAME="${LB_SCHEMANAME}" -f clonecreateschema.sql

  # Deploy to ephemeral database
  Tag-and-Deploy-to-EphemeralDB:
    actions:
      - type: liquibase
        command: tag
        cmdArgs: { URL: "${CLONED_URL}", tag: "${TAG}" }
        
      # Run the update (with testing rollback)
      - type: liquibase
        command: update-testing-rollback
        cmdArgs: { URL: "${CLONED_URL}", reports-name: "clone-report.html" }

      - type: liquibase
        command: history
        cmdArgs: { URL: "${CLONED_URL}" }
        
#endStage:
  #actions:
   # Drop Ephemeral Database if it exists   
    #- type: shell
      #command: |
        #snowsql -a $ACCT_NAME --username $CLONED_UID --dbname $CLONED_DB --schemaname $CLONED_SCHEMA -D S_NAME=$CLONED_SCHEMA -f clonedropschema.sql