##########           LIQUIBASE FLOWFILE                ##########
##########  learn more http://docs.liquibase.com/flow  ##########
globalVariables:
  ### Files
  ### Use absolute paths when using Liquibase's Docker container
  ###
  BASE_DIR: "./"
  ENV: ${LB_ENVIRONMENT}

stages:

  ## The first stage of actions
  Default:
    actions:
    
      # Show Status
      #
      - type: liquibase
        command: status

      ##
      #  Create clone
      #
      # - type: liquibase
      #  command: flow
      #  cmdArgs: {flowFile: "clone-setup.yaml"}
      #
      # Review pending changes
      #
      #- type: liquibase
      #  command: updateSQL
      #  cmdArgs: { URL: "${CLONED_URL}", USERNAME: "${CLONED_UID}", PASSWORD: "${CLONED_PW}" }
      #
      # Update the database
      #
      #- type: liquibase
      #  command: update
      #  cmdArgs: { URL: "${CLONED_URL}", USERNAME: "${CLONED_UID}", PASSWORD: "${CLONED_PW}" }
      #
      # Validate rollback
      #
      #- type: liquibase
      #  command: rollback-one-update-SQL
      #  cmdArgs: { URL: "${CLONED_URL}", USERNAME: "${CLONED_UID}", PASSWORD: "${CLONED_PW}" }
      #
      #
      # Execute rollback
      #
      #- type: liquibase
      #  command: rollback-one-update
      #  cmdArgs: { URL: "${CLONED_URL}", USERNAME: "${CLONED_UID}", PASSWORD: "${CLONED_PW}", force: "true" }
      #
      # Update the database
      #
      #- type: liquibase
      #  command: update
      #
      

## do these actions after all flow commands, regardless of whether the above commands were successful
endStage:
  actions:
    - type: liquibase
      command: history
    #- type: liquibase
    #  command: flow
    #  cmdArgs: { flowFile: "clone-cleanup.yaml"}